In [95]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.3.5


## Numpy Arrays

### Basic Array Creation

In [96]:
arr = np.array([1, 2, 3, 4, 5]) # Create a NumPy array from a list
print("Array:", arr)
a = [1, 2, 3, "j"] # Create a list with mixed data types
arr1 = np.array(a)
print(arr1)

Array: [1 2 3 4 5]
['1' '2' '3' 'j']


In [97]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) # Create a 2D NumPy array (matrix) from a list of lists
print("2D Array:\n", arr_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


### Array generation function

In [98]:
arr = np.arange(1, 11) # Create a NumPy array with values from 1 to 10 (exclusive)
print("Array:", arr)

arr1 = np.arange(1, 11, 2) # Create a NumPy array with values from 1 to 10 (exclusive) and a step of 2
print("Array with step 2:", arr1)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Array with step 2: [1 3 5 7 9]


In [99]:
arr = np.zeros(6)
print("Array of zeros:", arr)

arr = np.zeros((2, 3))
print("2D Array of zeros:\n", arr)

Array of zeros: [0. 0. 0. 0. 0. 0.]
2D Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [100]:
arr = np.ones(5) # Create a NumPy array of ones with length 5
print("Array with ones:\n", arr)

arr = np.ones((3, 4)) # Create a 2D NumPy array of ones with shape (3, 4)
print("2D Array with ones:\n", arr)

Array with ones:
 [1. 1. 1. 1. 1.]
2D Array with ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [101]:
arr = np.linspace(1, 20, 5) # Create a NumPy array with 5 linearly spaced values between 1 and 20 (inclusive)
print("Linearly spaced array:", arr)

Linearly spaced array: [ 1.    5.75 10.5  15.25 20.  ]


### Random Generation Function

In [102]:
arr = np.random.rand(4) # Create a NumPy array with 4 random values between 0 and 1 (uniform distribution)
print("Random array:", arr)

arr1 = np.random.randn(10) # Create a NumPy array with 10 random values from a standard normal distribution (mean=0, std=1)
print("Random array with normal distribution:", arr1)

Random array: [0.72535718 0.93421831 0.86538824 0.68597069]
Random array with normal distribution: [-3.70857593e-01 -2.79687249e-02  2.56516701e-01  3.05738493e-04
 -5.18643091e-01 -7.26732557e-01  2.16718633e+00  8.92099639e-01
  2.15639543e-01 -8.73158822e-01]


In [103]:
arr = np.random.randint(6) # Create a random integer between 0 and 5 (exclusive)
print("Random integer between 0 and 5:", arr)

arr = np.random.randint(10, 20, 10) # Create a NumPy array with 10 random integers between 10 and 20 (exclusive)
print("Random integer between 10 and 19:", arr)

Random integer between 0 and 5: 0
Random integer between 10 and 19: [19 16 10 13 10 15 19 11 16 13]


### Array Attributes

In [104]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original array:\n", arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [105]:
arr.shape # Get the shape of the array (number of rows and columns)

(3, 3)

In [106]:
arr.size # Get the total number of elements in the array

9

In [107]:
arr.dtype # Get the data type of the array elements

dtype('int64')

### Array Methods

In [108]:
arr.min()

np.int64(1)

In [109]:
arr.max()

np.int64(9)

In [110]:
arr.sum()

np.int64(45)

In [111]:
np.sum(arr, axis=0)  # Sum along columns

array([12, 15, 18])

In [112]:
np.sum(arr, axis=1)  # Sum along rows

array([ 6, 15, 24])

In [113]:
arr.mean() # Calculate the mean of all elements in the array

np.float64(5.0)

In [114]:
arr.std()

np.float64(2.581988897471611)

In [115]:
arr.argmin()  # Index of minimum value

np.int64(0)

In [116]:
arr.argmax()  # Index of maximum value

np.int64(8)

In [117]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [118]:
arr.reshape(2, 15) # Reshape the array to have 2 rows and 15 columns (total elements must remain the same)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

## Array indexing and slicing

### Numpy indexing and slicing of vectors

In [119]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [120]:
arr[2:6] # Elements from index 2 to 5

array([13, 14, 15, 16])

In [121]:
arr[2:6:2] # Every second element from index 2 to 5

array([13, 15])

In [122]:
arr[3:] # Elements from index 3 to the end

array([14, 15, 16, 17, 18, 19, 20])

In [123]:
arr[3::2] # Every second element from index 3 to the end 

array([14, 16, 18, 20])

### Numpy matrix indexing & slicing

In [124]:
arr = np.arange(1, 31).reshape(6, 5) # Create a 2D array with 6 rows and 5 columns
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [125]:
arr[0, 0]

np.int64(1)

In [126]:
arr[0, 4]

np.int64(5)

In [127]:
arr[0:2, 1:3] # Subarray from rows 0 to 1 and columns 1 to 2

array([[2, 3],
       [7, 8]])

In [128]:
arr[3:, 3:] # Subarray from rows 3 to 4 and columns 3 to 4

array([[19, 20],
       [24, 25],
       [29, 30]])

In [129]:
arr[:, 2] # All rows, column 2 (third column)

array([ 3,  8, 13, 18, 23, 28])

### Boolean Indexing

In [130]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [131]:
bool_index = arr % 2 == 0 # Create a boolean index for even numbers in the array
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [132]:
a = arr[bool_index] # Use the boolean index to filter the array and get only the even numbers
a

array([12, 14, 16, 18, 20])

In [133]:
a1 = arr[~bool_index] # Using ~ to get odd numbers
a1

array([11, 13, 15, 17, 19])

## Array Operations

### Arithmetic operations

In [134]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [135]:
a = a1 + a2
a

array([ 7,  9, 11, 13, 15])

In [136]:
a = a2 - a1
a

array([5, 5, 5, 5, 5])

In [137]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [138]:
a2/a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [139]:
a2//a1 # Floor division (integer division) of a2 by a1

array([6, 3, 2, 2, 2])

In [140]:
a1**a2 # Element-wise exponentiation: each element of a1 raised to the power of the corresponding element in a2

array([      1,     128,    6561,  262144, 9765625])

### Broadcasting

In [141]:
l = [10, 20, 30, 40, 50]
arr = np.array(l)
arr

array([10, 20, 30, 40, 50])

In [142]:
[x + 10 for x in l] # List comprehension to add 10 to each element in the list

[20, 30, 40, 50, 60]

In [143]:
arr + 10

array([20, 30, 40, 50, 60])

In [144]:
arr2 = np.arange(1, 26).reshape(5, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [145]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

### Deep & Shallow Copy

### shallow copy

In [146]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [147]:
slice_a = a[:5]
slice_a

array([1, 2, 3, 4, 5])

In [148]:
slice_a * 10 # This modifies the slice, but not the original array a

array([10, 20, 30, 40, 50])

In [149]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [150]:
a[4:6] * 10 # This does not modify the original array a

array([50, 60])

In [151]:
b = a.copy() # This creates a new array that is a copy of a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [152]:
b[0] = 100
print("Array a:", a)
print("Array b:", b)

Array a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Array b: [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


### deep copy

In [153]:
b = a # This creates a reference, not a copy
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [154]:
b[0] = 100
print("Array a:", a)
print("Array b:", b)

Array a: [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
Array b: [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


### Matrix operations

In [155]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Array A:\n", A)
print("Array B:\n", B)

Array A:
 [[1 2]
 [3 4]]
Array B:
 [[5 6]
 [7 8]]


In [156]:
A*B # Element-wise multiplication

array([[ 5, 12],
       [21, 32]])

In [157]:
A @ B # Matrix multiplication using @ operator

array([[19, 22],
       [43, 50]])

In [158]:
np.dot(A, B) # Matrix multiplication using np.dot

array([[19, 22],
       [43, 50]])

In [159]:
A.T # Transpose of A

array([[1, 3],
       [2, 4]])

### Advance Array Manipulation

In [160]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("Array a:", a)
print("Array b:", b)

Array a: [1 2 3 4]
Array b: [5 6 7 8]


In [161]:
np.vstack((a, b)) # Vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [162]:
np.hstack((a, b)) # Horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [163]:
np.vstack((A, B)) # Vertical stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [164]:
np.hstack((A, B)) # Vertical stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [165]:
np.column_stack((a, b)) # Column stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Splitting Array

In [166]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [167]:
np.split(c, 2) # Split into 2 sub-arrays along the first axis (rows)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [168]:
np.split(c, 2, axis=1) # Split into 2 sub-arrays along the second axis (columns)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [169]:
np.hsplit(c, 2) # Split into 2 sub-arrays along the second axis (columns)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [170]:
np.hsplit(c, 4) # Split into 4 sub-arrays along the second axis (columns)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [171]:
np.vsplit(c, 2) # Split into 2 sub-arrays along the first axis (rows)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [172]:
np.vsplit(c, 4) # Split into 4 sub-arrays along the first axis (rows)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

## Numpy Exercise

### Valid Sudoku

In [173]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [174]:
s1 = np.sum(s, axis = 0)

for x in s1:
    if x != 45:
        print("Not a valid sudoku")
        r = 1
        break

s2 = np.sum(s, axis = 1)

for x in s2:
    if x != 45:
        print("Not a valid sudoku")
        r = 1
        break


for i in range(0,9,3):
    for j in range(0,9,3):
        np.sum(s[i:i+3,j:j+3]) != 45
        r = 1
        break
    
if r != 0:
    print("Valid sudoku")


Valid sudoku


### General Questions

In [175]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]

data = np.array([
    [18, 85, 78], # Student 1
    [19, 92, 88], # Student 2
    [17, 76, 95], # Student 3
    [18, 65, 70], # Student 4
    [20, 90, 85]  # Student 5
])

In [176]:
# Get the shape of the matrix.

data.shape

(5, 3)

In [177]:
# Find the average age of the students.
arr = data[:,0]
print("Ages of students:", arr)
average_age = arr.mean()
print("Average age of students:", average_age)

Ages of students: [18 19 17 18 20]
Average age of students: 18.4


In [178]:
# Extract Math marks of all students.
data [:,1]

array([85, 92, 76, 65, 90])

In [179]:
# Find the highest Science marks.

np.max(data[:,2])

np.int64(95)

In [180]:
# Get details of students who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [181]:
# Increase Math marks of all students by 5.

data[:,1] = data[:,1] + 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [182]:
# Find how many students are younger than 19.

len(data[data[:,0] < 19])

3

In [183]:
# Calculate the average marks in each subject (Column-wise).
Math_avg = data[:,1].mean()
Science_avg = data[:,2].mean()
print("Average Math marks:", Math_avg)
print("Average Science marks:", Science_avg)

Average Math marks: 86.6
Average Science marks: 83.2


In [184]:
# OR

np.mean(data[:,1:], axis = 0)

array([86.6, 83.2])

In [185]:
# Get data of students who scored atleast 80 in both Math and Science.

data[(data[:,1] >= 80) & (data[:,2] >= 80)][:,0]

array([19, 17, 20])

In [186]:
# Replace all Science marks < 75 with 0.

data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])

In [187]:
# OR

data[:,2] = [0 if data[x,2] < 75 else data[x,2] for x in range(0, len(data)) ]
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]


In [188]:
# OR

for x in data:
    if x[2] < 75:
        x[2] = 0
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70  0]
 [20 95 85]]
